"use client";
import React, { useEffect, useRef } from "react";
import { CashoutLocation, CashoutPredictionItem } from "@/lib/types";

export function LeafletMap({ locations=[], predictions=[], selectedLocationId, onSelectLocation, height="420px", center=[28.6139,77.209], zoom=12 }: { locations?:CashoutLocation[]; predictions?:CashoutPredictionItem[]; selectedLocationId?:string; onSelectLocation?:(id:string)=>void; height?:string; center?:[number,number]; zoom?:number }) {
  const ref=useRef<HTMLDivElement>(null); const mapRef=useRef<any>(null); const layersRef=useRef<any[]>([]);
  useEffect(()=>{ let mounted=true; import("leaflet").then(L=>{ if(!mounted||!ref.current)return; if(!mapRef.current){ mapRef.current=L.map(ref.current,{center,zoom,zoomControl:false}); L.control.zoom({position:"bottomright"}).addTo(mapRef.current); L.tileLayer("https://{s}.basemaps.cartocdn.com/light_all/{z}/{x}/{y}{r}.png",{attribution:"&copy; OpenStreetMap &copy; CARTO",maxZoom:19}).addTo(mapRef.current); } else mapRef.current.setView(center,zoom); layersRef.current.forEach(x=>x.remove()); layersRef.current=[]; const map=mapRef.current;
    locations.forEach(loc=>{ const high=loc.historical_fraud_count>=10; const marker=L.circleMarker([loc.latitude,loc.longitude],{radius:high?10:7,fillColor:high?"#ef4444":"#22d3ee",color:"#071019",weight:2,fillOpacity:.85}); marker.addTo(map); marker.bindPopup(`<div style="font-size:12px"><b>${loc.name}</b><br/><span style="color:#94a3b8">${loc.type} · ${loc.bank}</span><br/><span style="color:#94a3b8">${loc.address}</span><br/><b style="color:${high?"#f87171":"#67e8f9"}">${loc.historical_fraud_count} historical incidents</b></div>`); layersRef.current.push(marker); });
    predictions.forEach(p=>{ const critical=p.risk_level==="CRITICAL"||p.probability_score>=.85; const selected=p.location_id===selectedLocationId; const icon=L.divIcon({className:"",html:`<div style="width:30px;height:30px;border-radius:50%;display:flex;align-items:center;justify-content:center;background:${selected?"#087b48":critical?"#c9483d":"#c17d20"};border:2px solid #fffdf8;box-shadow:0 0 18px ${selected?"rgba(8,123,72,.28)":critical?"rgba(201,72,61,.24)":"rgba(193,125,32,.22)"};color:#fff;font:700 11px ui-monospace">${p.rank}</div>`,iconSize:[30,30],iconAnchor:[15,15]}); const marker=L.marker([p.latitude,p.longitude],{icon}).addTo(map); marker.bindPopup(`<div style="font-size:12px"><b>#${p.rank} ${p.name}</b><br/><span style="color:#94a3b8">${p.type} · ${p.bank}</span><br/><b style="color:${critical?"#f87171":"#fbbf24"}">${(p.probability_score*100).toFixed(1)}% confidence</b><br/><span style="color:#94a3b8">${p.distance_km.toFixed(1)} km · ${p.estimated_time_window}</span></div>`); if(onSelectLocation)marker.on("click",()=>onSelectLocation(p.location_id)); layersRef.current.push(marker); });
  }); return()=>{mounted=false}; },[locations,predictions,selectedLocationId,center,zoom,onSelectLocation]);
  return <div ref={ref} style={{height,width:"100%"}} className="relative z-0 overflow-hidden rounded-2xl border border-white/[0.07]"/>;
}
